spring:
  application:
    name: HospitalBloodBank
  servlet:
    multipart:
      # 确保请求和文件的大小都限制在10MB以内
      max-file-size: 10MB
      max-request-size: 10MB
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/HospitalBloodBank
    username: root
    password: 20001209
server:
  address: 0.0.0.0
  port: 8083
#  servlet:
#    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true   # _驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  type-aliases-package: com.example.entity


